slug: crea-una-landing-sencilla-de-prueba-con-titulo-subtitulo-y-boton
source_paths:
- apps/crea-una-landing-sencilla-de-prueba-con-titulo-subtitulo-y-boton/README.md
- apps/crea-una-landing-sencilla-de-prueba-con-titulo-subtitulo-y-boton/app.meta.yaml
- apps/crea-una-landing-sencilla-de-prueba-con-titulo-subtitulo-y-boton/deploy.meta.yaml
last_sync_at: '2026-03-08T18:02:57.680490Z'
rag_sync_status: in_sync
signature: 52512a03dad6769802e14a633d5ac84f7f9535511fed60b5ac3a3117615796ac
document_id: 44ba860c-f009-4ad3-97c0-994bcbffb63a
notes: null
