slug: crea-una-landing-de-prueba-muy-simple-con-titulo-subtitulo-y-un-boton
source_paths:
- apps/crea-una-landing-de-prueba-muy-simple-con-titulo-subtitulo-y-un-boton/README.md
- apps/crea-una-landing-de-prueba-muy-simple-con-titulo-subtitulo-y-un-boton/app.meta.yaml
- apps/crea-una-landing-de-prueba-muy-simple-con-titulo-subtitulo-y-un-boton/deploy.meta.yaml
last_sync_at: '2026-03-08T18:06:19.003817Z'
rag_sync_status: in_sync
signature: e52a48d157bb95d6736f62b45f0e21913294a92bb2320a1d7b46f6c144bd2445
document_id: 2d31b1b6-a300-4293-83a4-bb560bb6bdf3
notes: null
