slug: hapi-ui-fd5e445c
source_paths:
- apps/hapi-ui-fd5e445c/README.md
- apps/hapi-ui-fd5e445c/app.meta.yaml
- apps/hapi-ui-fd5e445c/deploy.meta.yaml
last_sync_at: '2026-03-09T00:27:09.113510Z'
rag_sync_status: in_sync
signature: 0a29fed9cd159b5708c9dfb4ffc554cf2aa6de289b1fc2ebc056627b315969d1
document_id: c4d17a5b-4d84-4d46-afa9-c6e6f3051372
notes: stack-probe direct validation
