slug: qa-hard-ui-194727
source_paths:
- apps/qa-hard-ui-194727/README.md
- apps/qa-hard-ui-194727/app.meta.yaml
- apps/qa-hard-ui-194727/deploy.meta.yaml
last_sync_at: '2026-03-08T19:47:28.621214Z'
rag_sync_status: in_sync
signature: 9a9e30ddb772dc2addd8ccfa7b5cd05b7aaa843d038a4ef0f6952d20edf51ba6
document_id: a603ebc6-cece-4fb6-914e-bb3a12c0c8f7
notes: null
