slug: sales-probe-fbfd9da2
source_paths:
- apps/sales-probe-fbfd9da2/README.md
- apps/sales-probe-fbfd9da2/app.meta.yaml
- apps/sales-probe-fbfd9da2/deploy.meta.yaml
last_sync_at: '2026-03-08T03:37:22.257343Z'
rag_sync_status: in_sync
signature: 51eececfe5bc4f7507abbcaa201d43da0ff35c1ff73579f856d1ae08770883f6
document_id: 1e7021ae-c10d-489b-8a86-f160c9adaee1
notes: null
