slug: sales-landing-batch
source_paths:
- apps/sales-landing-batch/README.md
- apps/sales-landing-batch/app.meta.yaml
- apps/sales-landing-batch/deploy.meta.yaml
last_sync_at: '2026-03-08T14:40:36.661823Z'
rag_sync_status: in_sync
signature: c4a8b8d0f3bc09cf1fb99f0f6b8dd2d5feeaded1b2593276592e3ceb28dea77f
document_id: 59b210fa-b73b-4353-9b69-3f7f4fa96eda
notes: null
