slug: sales-probe-679afd2d
source_paths:
- apps/sales-probe-679afd2d/README.md
- apps/sales-probe-679afd2d/app.meta.yaml
- apps/sales-probe-679afd2d/deploy.meta.yaml
last_sync_at: '2026-03-08T04:17:31.990073Z'
rag_sync_status: in_sync
signature: 8a2ffa7471c778fffe5f2b5cb3ee2bb8d1b0d66249d6f5c3923e6d738a146e48
document_id: 0a4b7e95-079c-42aa-9fe7-9bb4af250df2
notes: null
