slug: sales-probe-bb7561ca
source_paths:
- sandboxes/sales-probe-bb7561ca/README.md
- sandboxes/sales-probe-bb7561ca/app.meta.yaml
- sandboxes/sales-probe-bb7561ca/deploy.meta.yaml
last_sync_at: '2026-03-08T01:58:28.817561Z'
rag_sync_status: in_sync
signature: fc0d203f7c701efc8d604da9903affeae2c5255333c21f07e4bc39c99220ed15
document_id: 8846c335-4c55-4da8-8b49-b7ee0231ef72
notes: null
