slug: sales-probe-1b04d3f5
source_paths:
- apps/sales-probe-1b04d3f5/README.md
- apps/sales-probe-1b04d3f5/app.meta.yaml
- apps/sales-probe-1b04d3f5/deploy.meta.yaml
last_sync_at: '2026-03-08T04:03:31.352561Z'
rag_sync_status: in_sync
signature: f8175574a81bac0d3aa9d2f443bf393c8e95befa089082b5c3cedd4e9b534abf
document_id: 7d30a8b8-5fde-433b-a459-8b1b0ae9b8bd
notes: null
