slug: smoke-landing-002
source_paths:
- apps/smoke-landing-002/README.md
- apps/smoke-landing-002/app.meta.yaml
- apps/smoke-landing-002/deploy.meta.yaml
last_sync_at: '2026-03-08T18:19:44.750679Z'
rag_sync_status: in_sync
signature: 51eecc9e7eaaa1f24cacbe436ca79de7ca73bb1e60c9a344d1d53771fa2dc115
document_id: cbda0622-ce01-4b2c-9381-d8007f8f48be
notes: null
