slug: smoke-landing-001
source_paths:
- apps/smoke-landing-001/README.md
- apps/smoke-landing-001/app.meta.yaml
- apps/smoke-landing-001/deploy.meta.yaml
last_sync_at: '2026-03-08T18:14:14.249762Z'
rag_sync_status: in_sync
signature: fc8fbdbf92a386bdac602f9916270a654ef4833ce9202b97462c9e66338e961b
document_id: 6ee4e4b9-a4f2-4dc8-bfdf-d15501fc4255
notes: null
